---
title: "Uso del tiempo de los ecuatorianos"
author: "Christian Salas Marquez"
date: "2022-03-17"
output: html_notebook
---

```{r}
###############################################################
####                   Descargar los datos                 ####
###############################################################

if(!require(tidyverse)) install.packages("tidyverse", repos = "http://cran.us.r-project.org")
if(!require(haven)) install.packages("haven", repos = "http://cran.us.r-project.org")
if(!require(readr)) install.packages("readr", repos = "http://cran.us.r-project.org")


```


```{r}
# Base de datos de personas ----------
# Le damos un nombre al url
url <- "https://github.com/christianjaviersalasmarquez/LIDE_ESPOL_Christian_Salas/raw/main/Base%20EUT%202012.zip"
# Creamos un directorio temporal
td <- tempdir()
# Creamos una carpeta temporal
tf <- tempfile(tmpdir=td, fileext = ".zip")
# Descargamos los discap en la carpeta temporal
download.file(url,tf)

```


```{r}
# Obtenemos el nombre del archivo dentro del archivo zip, lo descomprimimos (unzip), obtenemos el nombre del 
# parche, y finalmente lo cargamos
EUT2012.f.name <- unzip(tf, list=TRUE)$Name[1] # El archivo SAV de la EUT 2012 es el primero
unzip(tf, files=EUT2012.f.name, exdir=td, overwrite=TRUE)
EUT2012.f.path <- file.path(td, EUT2012.f.name)
uso_del_tiempo_2012 <- read_sav(EUT2012.f.path)
```


```{r}
#data_UT2012 <- uso_del_tiempo_2012
data_UT2012 <- data.frame(uso_del_tiempo_2012)
```



```{r}
uso_del_tiempo_2019 <- read.csv2("https://raw.githubusercontent.com/christianjaviersalasmarquez/LIDE_ESPOL_Christian_Salas/main/201912_multibdd_uso_del_tiempo.sav.csv", header = FALSE)
```


```{r}
personas_2019 <- read.csv2("https://raw.githubusercontent.com/christianjaviersalasmarquez/LIDE_ESPOL_Christian_Salas/main/201912_multibdd_personas.sav.csv", header = FALSE)
```








```{r}
header_true <- function(df) {
  names(df) <- as.character(unlist(df[1,]))
  df[-1,]
}

```

```{r}
data_UT2019 <- header_true(uso_del_tiempo_2019)

colnames(data_UT2019)[1] <- 'area'
```

```{r}
data_personas2019 <- header_true(personas_2019)

colnames(data_personas2019)[1] <- 'area'
```




# 2012

```{r}
# Histograma de las edades

hist(data_UT2012$P03)

```


```{r}
t_trabajo_mercado_laboral <- data_UT2012 %>%
  rowwise() %>%
  mutate(tiempo_trabajo_mercadolaboral = sum(as.numeric(P19A), (as.numeric(P19B)/60),as.numeric(P19C), (as.numeric(P19D)/60), na.rm = TRUE))

```


```{r}
tiempo_trabajo <- t_trabajo_mercado_laboral$tiempo_trabajo_mercadolaboral

ggplot(t_trabajo_mercado_laboral, aes(x =tiempo_trabajo_mercadolaboral )) + geom_histogram()

```





# 2019

```{r}
# Histograma de las edades 2019
hist(as.numeric(df_analisis_UT2019$s1p3))
```


```{r}
#Merge de la base de datos de uso del tiempo con la de personas, para conocer información sobre la persona

df_info_personas2019 <- data.frame(id_per = data_personas2019$id_per, s1p2 = data_personas2019$s1p2, s1p3 = data_personas2019$s1p3)

df_analisis_UT2019 <- merge(df_info_personas2019, data_UT2019, by = "id_per")

```



De los encuestados, ¿Cuántos respondieron que sí participan en los quehaceres del hogar y cuantos no?


```{r}
s51p1_2019 <- data_UT2019$s51p1
s51p1_2019_factor <- factor(data_UT2019$s51p1)
levels(s51p1_2019_factor) <- c("Si","No")
summary(s51p1_2019_factor)
```



```{r}
#s51p1_2019 <- df_analisis_UT2019$s51p1
#s51p1_2019_factor <- factor(df_analisis_UT2019$s51p1)
#levels(s51p1_2019_factor) <- c("Si","No")

#s1p2_2019_factor <- factor(df_analisis_UT2019$s1p2)
#levels(s1p2_2019_factor) <- c("Hombre","Mujer")

#summary(s51p1_2019_factor)
#summary(s1p2_2019_factor)



```


```{r}
# Summarize() con summary()
# Participa en quehaceres del hogar? Por sexo
df_hogar_sexo <- df_analisis_UT2019 %>%
  group_by(s1p2_factor, participacion = fct_recode(factor(s51p1), "Si" = "1", "No" = "2" )) %>%
  summarize(conteo_actividades_hogar = summary(factor(s51p1)))

df_hogar_sexo
```

```{r}
# Summarize() con length también funciona igual
# Participa en quehaceres del hogar? Por sexo
#df_hogar_sexo <- df_analisis_UT2019 %>%
#  group_by(s1p2_factor,fct_recode(factor(s51p1), "Si" = "1", "No" = "2" )) %>%
#  summarize(conteo_actividades_hogar = length(factor(s51p1)))

# df_hogar_sexo
```

```{r}
# Validacion cantidad de Si o No en s51p1: Success

#summary(fct_recode(factor(data_UT2019$s51p1), "Si" = "1", "No"="2"))[1] ==  df_hogar_sexo$conteo_actividades_hogar[1] + df_hogar_sexo$conteo_actividades_hogar[3]

#summary(fct_recode(factor(data_UT2019$s51p1), "Si" = "1", "No"="2"))[2] == df_hogar_sexo$conteo_actividades_hogar[2] + df_hogar_sexo$conteo_actividades_hogar[4]



# summary(factor(data_UT2019$s51p1))[1] + summary(factor(data_UT2019$s51p1))[2] # Cantidad de respuesta Si + No 33236

```



```{r}
# Validación cantidad de hombres y mujeres en s1p2: Success
# El conteo en el summarize() funciona tanto con summary() como con length()

#summary(factor(df_analisis_UT2019$s1p2))[1] == df_hogar_sexo$conteo_actividades_hogar[1] + df_hogar_sexo$conteo_actividades_hogar[2]

#summary(factor(df_analisis_UT2019$s1p2))[2] == df_hogar_sexo$conteo_actividades_hogar[3] + df_hogar_sexo$conteo_actividades_hogar[4]

# summary(factor(df_analisis_UT2019$s1p2))[1] + summary(factor(df_analisis_UT2019$s1p2))[2] # Cantidad de Hombres + Mujeres en data_UT2019 33236


```



```{r}
# ¿Participa en los quehaceres del hogar? Respuestas de Hombres y Mujeres
ggplot(df_hogar_sexo, aes(x = s1p2_factor, y = conteo_actividades_hogar, fill = participacion)) + geom_bar(stat = 'identity')
```


```{r}
ggplot(df_hogar_sexo, aes(x = s1p2_factor, y = conteo_actividades_hogar, fill = participacion)) + geom_bar(stat = 'identity', position = 'dodge')
```




# Comparaciones 2012 y 2019




```{r}
# 2012
# EN LA SEMANA PASADA: ¿Cocinó o preparó alimentos para consumirse en el desayuno, almuerzo, merienda, entre comidas, incluyendo comidas para llevar?

UT15_2012 <- data_UT2012$UT15

UT15_2012 <- factor(UT15_2012)

#str(UT15_2012)
#class(UT15_2012)

summary(UT15_2012)

# dim(data_UT2012[1])[1] == summary(UT15_2012)[1] + summary(UT15_2012)[2] + summary(UT15_2012)[3]



```


```{r}
df_analisis_UT15_UT2012 <- data.frame(P02_factor = fct_recode(factor(data_UT2012$P02), "Hombre" = "1", "Mujer"="2") , CIUDAD = data_UT2012$CIUDAD, UT15 = data_UT2012$UT15 , UT15_factor = fct_recode(factor(data_UT2012$UT15), "Si"="1","No"="2" ) , UT15A = data_UT2012$UT15A, UT15B = data_UT2012$UT15B, UT15C = data_UT2012$UT15C, UT15D = data_UT2012$UT15D)
```

```{r}
# SUCCESS

df_cocina_sexo_2012 <- df_analisis_UT15_UT2012 %>%
  group_by( P02_factor , UT15_factor ) %>%
  summarize(conteo_cocina = summary( factor(UT15) ))

df_cocina_sexo_2012
# Hay 11623 hombres con NA y 10835 mujeres con NA. Sumando el total de 22458 de la pregunta UT15

```

```{r}
#df_analisis_UT15_UT2012 %>%
#  group_by( P02_factor , UT15_factor ) %>%
#  summarize(conteo_cocina = summary( UT15_factor ))

# Funciona pero resulta en filas adicionales innecesarias
```


```{r}
ggplot(df_cocina_sexo_2012, aes(x = P02_factor, y = conteo_cocina, fill =  UT15_factor)) + geom_bar(stat = 'identity', position = 'dodge')

# Pensar en considerar las edades o rango de edades

```




```{r}
# 2019
# La semana pasada... Cocinó o preparó alimentos para consumirse en el desayuno, almuerzo, merienda, entre comidas, incluyendo comidas para llevar?

df_analisis_UT2019$s1p2_factor <- fct_recode(factor(df_analisis_UT2019$s1p2), "Hombre"="1","Mujer"="2" )
df_analisis_UT2019$s51p2_factor <- fct_recode(factor(df_analisis_UT2019$s51p2), "Si"="1","No"="2" ) 

df_cocina_sexo_2019 <- df_analisis_UT2019 %>%
  group_by(s1p2_factor, s51p2_factor) %>%
  summarize(conteo_cocina = summary( factor(s1p2)  ) )  #Resulta el mismo conteo si se coloca factor(s1p2) o factor(s51p2) en el summary

df_cocina_sexo_2019

```


```{r}
# Validacion df_cocina_sexo_2019: Success

#summary( fct_recode( factor(df_analisis_UT2019$s1p2), "Hombre"="1","Mujer"="2" ) )[1] == df_cocina_sexo_2019[1,3] + df_cocina_sexo_2019[2,3] + df_cocina_sexo_2019[3,3]

#summary( fct_recode( factor(df_analisis_UT2019$s1p2), "Hombre"="1","Mujer"="2" ) )[2] == df_cocina_sexo_2019[4,3] + df_cocina_sexo_2019[5,3] + df_cocina_sexo_2019[6,3]


```


```{r}
# Considerando NA values
ggplot(df_cocina_sexo_2019, aes(x = s1p2_factor, y = conteo_cocina, fill = s51p2_factor)) + geom_bar(stat = 'identity', position = 'dodge')

# Pensar en considerar las edades o rango de edades

```













